with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName | firstUpper}}"
outpkg: mocks
packages:
  linkTraccer/internal/domain/tgbot:
    config:
      dir: mocks
    interfaces:
      BotService:
