with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName | firstUpper}}"
outpkg: mocks
packages:
  linkTraccer/internal/application/botService:
    config:
      dir: mocks
    interfaces:
      TgClient:
  linkTraccer/internal/infrastructure/siteClients/stackoverflow:
    config:
      dir: mocks
    interfaces:
      HTTPClient:
  linkTraccer/internal/application/scrapperService:
    config:
      dir: mocks
    interfaces:
      UserRepo:
      SiteClient:
      BotClient:
