with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName | firstUpper}}"
outpkg: mocks
packages:
  linkTraccer/internal/application/botService:
    config:
      dir: mocks
    interfaces:
      TgClient:
