services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=postgres
      - POSTGRES_DB=linkTraccer
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d linkTraccer" ]
      interval: 3s
      timeout: 5s
      retries: 10

  migrations:
    image: migrate/migrate
    container_name: migrations
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      -path /migrations
      -database "postgres://postgres:1234@postgres:5432/linkTraccer?sslmode=disable" up
