services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d linkTraccer" ]
      interval: 3s
      timeout: 5s
      retries: 10

  migrations:
    image: migrate/migrate
    container_name: migrations
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command:
      -path /migrations
      -database "postgres://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}?sslmode=disable" up
