// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	scrapper "linkTraccer/internal/domain/scrapper"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SiteClient is an autogenerated mock type for the SiteClient type
type SiteClient struct {
	mock.Mock
}

type SiteClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SiteClient) EXPECT() *SiteClient_Expecter {
	return &SiteClient_Expecter{mock: &_m.Mock}
}

// CanTrack provides a mock function with given fields: link
func (_m *SiteClient) CanTrack(link string) bool {
	ret := _m.Called(link)

	if len(ret) == 0 {
		panic("no return value specified for CanTrack")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SiteClient_CanTrack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanTrack'
type SiteClient_CanTrack_Call struct {
	*mock.Call
}

// CanTrack is a helper method to define mock.On call
//   - link string
func (_e *SiteClient_Expecter) CanTrack(link interface{}) *SiteClient_CanTrack_Call {
	return &SiteClient_CanTrack_Call{Call: _e.mock.On("CanTrack", link)}
}

func (_c *SiteClient_CanTrack_Call) Run(run func(link string)) *SiteClient_CanTrack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *SiteClient_CanTrack_Call) Return(_a0 bool) *SiteClient_CanTrack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SiteClient_CanTrack_Call) RunAndReturn(run func(string) bool) *SiteClient_CanTrack_Call {
	_c.Call.Return(run)
	return _c
}

// LinkUpdates provides a mock function with given fields: link, updatesSince
func (_m *SiteClient) LinkUpdates(link string, updatesSince time.Time) ([]*scrapper.LinkUpdate, error) {
	ret := _m.Called(link, updatesSince)

	if len(ret) == 0 {
		panic("no return value specified for LinkUpdates")
	}

	var r0 []*scrapper.LinkUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time) ([]*scrapper.LinkUpdate, error)); ok {
		return rf(link, updatesSince)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time) []*scrapper.LinkUpdate); ok {
		r0 = rf(link, updatesSince)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*scrapper.LinkUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(link, updatesSince)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SiteClient_LinkUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkUpdates'
type SiteClient_LinkUpdates_Call struct {
	*mock.Call
}

// LinkUpdates is a helper method to define mock.On call
//   - link string
//   - updatesSince time.Time
func (_e *SiteClient_Expecter) LinkUpdates(link interface{}, updatesSince interface{}) *SiteClient_LinkUpdates_Call {
	return &SiteClient_LinkUpdates_Call{Call: _e.mock.On("LinkUpdates", link, updatesSince)}
}

func (_c *SiteClient_LinkUpdates_Call) Run(run func(link string, updatesSince time.Time)) *SiteClient_LinkUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Time))
	})
	return _c
}

func (_c *SiteClient_LinkUpdates_Call) Return(_a0 []*scrapper.LinkUpdate, _a1 error) *SiteClient_LinkUpdates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SiteClient_LinkUpdates_Call) RunAndReturn(run func(string, time.Time) ([]*scrapper.LinkUpdate, error)) *SiteClient_LinkUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// NewSiteClient creates a new instance of SiteClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSiteClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SiteClient {
	mock := &SiteClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
